// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BeerTents.iOS {
	
	
	// Base type probably should be MonoTouch.UIKit.UIViewController or subclass
	[MonoTouch.Foundation.Register("TentCellController")]
	public partial class TentCellController {
		
		private MonoTouch.UIKit.UILabel __mt_brewery;
		
		private MonoTouch.UIKit.UILabel __mt_name;
		
		private MonoTouch.UIKit.UITableViewCell __mt_cell;
		
		#pragma warning disable 0169
		[MonoTouch.Foundation.Connect("brewery")]
		private MonoTouch.UIKit.UILabel brewery {
			get {
				this.__mt_brewery = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("brewery")));
				return this.__mt_brewery;
			}
			set {
				this.__mt_brewery = value;
				this.SetNativeField("brewery", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("name")]
		private MonoTouch.UIKit.UILabel name {
			get {
				this.__mt_name = ((MonoTouch.UIKit.UILabel)(this.GetNativeField("name")));
				return this.__mt_name;
			}
			set {
				this.__mt_name = value;
				this.SetNativeField("name", value);
			}
		}
		
		[MonoTouch.Foundation.Connect("cell")]
		private MonoTouch.UIKit.UITableViewCell cell {
			get {
				this.__mt_cell = ((MonoTouch.UIKit.UITableViewCell)(this.GetNativeField("cell")));
				return this.__mt_cell;
			}
			set {
				this.__mt_cell = value;
				this.SetNativeField("cell", value);
			}
		}
	}
}
