// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace BeerTents.Android
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f070001
			public const int bottomtext = 2131165185;
			
			// aapt resource value: 0x7f070003
			public const int brewery = 2131165187;
			
			// aapt resource value: 0x7f070002
			public const int brewery_header = 2131165186;
			
			// aapt resource value: 0x7f070007
			public const int phone = 2131165191;
			
			// aapt resource value: 0x7f070006
			public const int phone_header = 2131165190;
			
			// aapt resource value: 0x7f070005
			public const int prop = 2131165189;
			
			// aapt resource value: 0x7f070004
			public const int prop_header = 2131165188;
			
			// aapt resource value: 0x7f070000
			public const int toptext = 2131165184;
			
			// aapt resource value: 0x7f070009
			public const int web = 2131165193;
			
			// aapt resource value: 0x7f070008
			public const int web_header = 2131165192;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int list_item = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int tentdetail = 2130903041;
			
			private Layout()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int tents = 2130968576;
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050000
			public const int app_name = 2131034112;
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int detail_title = 2131099648;
			
			private Style()
			{
			}
		}
	}
}
